# Generated by Django 5.1.6 on 2025-02-25 11:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_rename_mazo_decks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Decks',
            new_name='Deck',
        ),
    ]
